import { extendObservable } from "mobx";

class ColDefinition {
    constructor() {
        extendObservable(this, {
            columnDefs: [
                {
                    headerName: "role_name",
                    field: "role_name",
                    checkboxSelection: false,
                },
                {
                    headerName: "recommended_title",
                    field: "recommended_title",
                },
                {
                    headerName: "role_description",
                    field: "role_description",
                },
                {
                    headerName: "role_family",
                    field: "role_family",
                },
                {
                    headerName: "org_level_1",
                    field: "org_level_1",
                },
                {
                    headerName: "org_level_2",
                    field: "org_level_2",
                },
                {
                    headerName: "org_level_3",
                    field: "org_level_3",
                },
                {
                    headerName: "pred_soc_1",
                    field: "pred_soc_1",
                },
                {
                    headerName: "pred_name1",
                    field: "pred_name1",
                },
                {
                    headerName: "pred_soc_2",
                    field: "pred_soc_2",
                },
                {
                    headerName: "pred_name2",
                    field: "pred_name2",
                },
                {
                    headerName: "pred_soc_3",
                    field: "pred_soc_3",
                },
                {
                    headerName: "pred_name3",
                    field: "pred_name3",
                },
                {
                    headerName: "compo_bracket",
                    field: "compo_bracket",
                },
                {
                    headerName: "total_fte",
                    field: "total_fte",
                },
                {
                    headerName: "has_reports_ratio",
                    field: "has_reports_ratio",
                },
                {
                    headerName: "has_mgr_reports_ratio",
                    field: "has_mgr_reports_ratio",
                },
                {
                    headerName: "New Job",
                    field: "New Job",
                },
                {
                    headerName: "Review Required",
                    field: "Review Required",
                },
                {
                    headerName: "Selected SOC Code",
                    field: "Selected SOC Code",
                },
                {
                    headerName: "Selected SOC Name",
                    field: "Selected SOC Name",
                },
                {
                    headerName: "Description",
                    field: "Description",
                },
            ],
            defaultColDef: {
                flex: 1,
                minWidth: 110,
                sortable: true,
                filter: true,
                editable: false,
                resizable: true,
            },
            rowData: [
                {
                    role_name:
                        "[ASST] MGR, CUST INSIGHTS & ANALYTICS, CUSTOMER RESPONSIVENESS DEPARTMENT",
                    recommended_title:
                        "Asst MGR Cust Insights and Analytics Customer Responsiveness Department",
                    role_description: "",
                    role_family: "",
                    org_level_1: "Service Delivery",
                    org_level_2: "Customer Insights and Analytics",
                    org_level_3: "",
                    pred_soc_1: "43-4051.00",
                    pred_name1: "Customer Service Representatives",
                    pred_soc_2: "43-6014.00",
                    pred_name2:
                        "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive",
                    pred_soc_3: "42-1046.00",
                    pred_name3:
                        "First-Line Supervisor of Customer Service Representatives",
                    compo_bracket: "Mid",
                    total_fte: 1,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
                {
                    role_name: "[Senior]Manager  (Service Centre)",
                    recommended_title: "Senior Manager",
                    role_description: "",
                    role_family: "",
                    org_level_1: "Service Delivery",
                    org_level_2: "Customer Service and Engagement",
                    org_level_3: "",
                    pred_soc_1: "42-1046.00",
                    pred_name1:
                        "First-Line Supervisor of Customer Service Representatives",
                    pred_soc_2: "43-3031.00",
                    pred_name2: "Bookkeeping, Accounting, and Auditing Clerks",
                    pred_soc_3: "42-1009.00",
                    pred_name3: "Project Managers",
                    compo_bracket: "Mid",
                    total_fte: 37,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
                {
                    role_name: "[Senior]Manager (Call Centre)",
                    recommended_title: "Senior Manager",
                    role_description: "",
                    role_family: "",
                    org_level_1: "Service Delivery",
                    org_level_2: "Customer Service and Engagement",
                    org_level_3: "",
                    pred_soc_1: "42-1046.00",
                    pred_name1:
                        "First-Line Supervisor of Customer Service Representatives",
                    pred_soc_2: "43-3031.00",
                    pred_name2: "Bookkeeping, Accounting, and Auditing Clerks",
                    pred_soc_3: "42-1009.00",
                    pred_name3: "Project Managers",
                    compo_bracket: "Mid",
                    total_fte: 37,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
                {
                    role_name: "AD,  Applications",
                    recommended_title: "AD Applications",
                    role_description: "",
                    role_family: "Regulatory Case Processing",
                    org_level_1: "Management",
                    org_level_2: "OPS",
                    org_level_3: "WPD",
                    pred_soc_1: "42-1042.00",
                    pred_name1: "Applications Services Managers",
                    pred_soc_2: "15-1132.00",
                    pred_name2: "Software Developers, Applications",
                    pred_soc_3: "42-1012.00",
                    pred_name3: "Interns",
                    compo_bracket: "Mid",
                    total_fte: 1,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
                {
                    role_name: "AD, Compliance Ops & Mgt",
                    recommended_title: "AD Compliance Operations and Mgt",
                    role_description:
                        "This team is responsible for driving the Employment Act compliance through effective detection, intervention and deterrence measures.",
                    role_family: "Enforcement & Compliance",
                    org_level_1: "Management",
                    org_level_2: "OPS",
                    org_level_3: "LRWD",
                    pred_soc_1: "42-1060.00",
                    pred_name1: "Compliance Officers",
                    pred_soc_2: "11-9199.02",
                    pred_name2: "Compliance Managers",
                    pred_soc_3: "43-9061.00",
                    pred_name3: "Office Clerks, General",
                    compo_bracket: "Mid",
                    total_fte: 1,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
                {
                    role_name: "AD, Construction & Process",
                    recommended_title: "AD Construction and Process",
                    role_description: "",
                    role_family: "Regulatory Case Processing",
                    org_level_1: "Management",
                    org_level_2: "OPS",
                    org_level_3: "WPD",
                    pred_soc_1: "43-9061.00",
                    pred_name1: "Office Clerks, General",
                    pred_soc_2: "25-9031.01",
                    pred_name2: "Instructional Designers and Technologists",
                    pred_soc_3: "11-9021.00",
                    pred_name3: "Construction Managers",
                    compo_bracket: "Mid",
                    total_fte: 1,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
                {
                    role_name: "AD, Corp Admin",
                    recommended_title: "AD Corporate Administration",
                    role_description: "",
                    role_family: "Corporate Administration",
                    org_level_1: "Management",
                    org_level_2: "CSG",
                    org_level_3: "CPMD",
                    pred_soc_1: "43-6014.00",
                    pred_name1:
                        "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive",
                    pred_soc_2: "43-9061.00",
                    pred_name2: "Office Clerks, General",
                    pred_soc_3: "15-1142.00",
                    pred_name3: "Network and Computer Systems Administrators",
                    compo_bracket: "Mid",
                    total_fte: 1,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
                {
                    role_name: "AD, Customer Ops (Manufacturing)",
                    recommended_title: "AD Customer Operations",
                    role_description: "",
                    role_family: "Regulatory Case Processing",
                    org_level_1: "Management",
                    org_level_2: "OPS",
                    org_level_3: "WPD",
                    pred_soc_1: "43-4051.00",
                    pred_name1: "Customer Service Representatives",
                    pred_soc_2: "42-1049.00",
                    pred_name2: "Customer Experience Analysts",
                    pred_soc_3: "43-9061.00",
                    pred_name3: "Office Clerks, General",
                    compo_bracket: "Mid",
                    total_fte: 8,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
                {
                    role_name: "Administrative Executive",
                    recommended_title: "Administrative Executive",
                    role_description: "",
                    role_family: "",
                    org_level_1: "Administration",
                    org_level_2: "General office management / administration support",
                    org_level_3: "",
                    pred_soc_1: "43-6014.00",
                    pred_name1:
                        "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive",
                    pred_soc_2: "43-6011.00",
                    pred_name2:
                        "Executive Secretaries and Executive Administrative Assistants",
                    pred_soc_3: "11-3011.00",
                    pred_name3: "Administrative Services Managers",
                    compo_bracket: "Low",
                    total_fte: 2,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
                {
                    role_name: "Administrative Executive ",
                    recommended_title: "Administrative Executive",
                    role_description: "",
                    role_family: "",
                    org_level_1: "Education",
                    org_level_2: "Non-teaching role",
                    org_level_3: "",
                    pred_soc_1: "43-6014.00",
                    pred_name1:
                        "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive",
                    pred_soc_2: "43-6011.00",
                    pred_name2:
                        "Executive Secretaries and Executive Administrative Assistants",
                    pred_soc_3: "11-3011.00",
                    pred_name3: "Administrative Services Managers",
                    compo_bracket: "Low",
                    total_fte: 2,
                    has_reports_ratio: "",
                    has_mgr_reports_ratio: "",
                    "New Job": "",
                    "Review Required": "",
                    "Selected SOC Code": "",
                    "Selected SOC Name": "",
                    Description: "",
                },
            ]
        });
    }
}

export default new ColDefinition();
